title: Lx
description: Knowledge dump
url: "https://lxyuan0420.github.io"
baseurl: ""

remote_theme: b2a3e8/jekyll-theme-console
style: light

header_pages:
  - index.md
  - about.md

footer: >-
  find me on <a href="https://github.com/LxYuan0420">github</a> ·
  <a href="https://www.linkedin.com/in/likxunyuan">linkedin</a> ·
  <a href="https://twitter.com/lxyuan">twitter</a>

permalink: posts/:slug

markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-remote-theme
